# Generated by Django 2.0.7 on 2018-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('e', 'Education'), ('w', 'Work'), ('x', 'Extracurricular')], max_length=1)),
                ('organization', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=75)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
