# Generated by Django 2.0.7 on 2018-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='experience',
            name='organization_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
    ]
