# Generated by Django 2.0.7 on 2018-07-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180728_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='logo_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
