# Generated by Django 2.0.7 on 2018-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20180729_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='languages',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('e', 'Education'), ('w', 'Work'), ('l', 'Leadership'), ('p', 'Project')], max_length=1),
        ),
    ]
