# Generated by Django 2.0.7 on 2018-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20180729_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=75)),
                ('project_link', models.CharField(max_length=100)),
                ('logo_url', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=75)),
                ('languages', models.CharField(max_length=75)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
