# Generated by Django 2.0.7 on 2018-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('e', 'Education'), ('w', 'Work'), ('l', 'Leadership')], max_length=1),
        ),
    ]
