# Generated by Django 2.0.7 on 2018-07-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20180729_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(choices=[('co', 'Core'), ('wb', 'Web'), ('ml', 'Data')], max_length=2)),
                ('skill_name', models.CharField(max_length=75)),
                ('proficiency', models.IntegerField(choices=[(1, 'Basic'), (3, 'Intermediate'), (5, 'Expert'), (2, 'Novice'), (4, 'Advanced')])),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
